import type { CapacitorConfig } from "@capacitor/cli";

/**
 * Capacitor wraps the existing web app in a native shell.
 *
 * The UI is BUNDLED with the app (webDir) rather than loaded from the deployed URL,
 * so the app opens with no network and renders my events straight from IndexedDB.
 * Only the server-backed features — share snapshots, comments, holidays — go over
 * the wire, as absolute calls to API_ORIGIN in calendar.js (allowed by middleware.ts).
 *
 * Trade-off: a web deploy no longer updates the native app instantly; ship a new
 * build to change the bundled UI. Run `npm run build:shell` (or `npm run cap:sync`)
 * after touching app/calendar-markup.ts, app/globals.css, or public/calendar.js.
 *
 * The native parts are the home-screen widgets + the WidgetBridge plugin (WIDGETS.md).
 */
const config: CapacitorConfig = {
  appId: "com.shareday.app",
  appName: "셰어데이",
  // generated by scripts/build-shell.mjs
  webDir: "capacitor-www",
  ios: {
    contentInset: "always",
  },
  android: {
    // custom scheme used by the widget deep link (shareday://calendar?token=…)
    allowMixedContent: false,
  },
};

export default config;
